---
title: "Trajectories in diversity and inclusion"
output: html_notebook
---

Libraries
# read in libraries
```{r, results='hide'}
util_libraries <- c("foreign", "reshape2", "stargazer", "arm", "plyr", "tidyverse", "stringr", "qdapRegex", "GGally", "progress", "pracma", "lubridate", "DescTools", "Matrix.utils", "irr", "psych", 'gtools')
vis_libraries  <- c("ggplot2", "ggrepel", "grid", "gridExtra", "RColorBrewer", "scales", "corrplot", "ggeffects", "cowplot", "plot.matrix", "corrgram", "ggnetwork", "vioplot", "dotwhisker", "sjPlot", "sjlabelled", "sjmisc", "plot3D")
stat_libraries <- c("network", "sna", "igraph", "moments", "nortest", "MASS", "randomForest", "sandwich", "lmtest", "gmodels", "margins", "sampleSelection", "pROC", "pscl",  "pwr", "relaimpo", "lme4", "plm", "caret", "ResourceSelection", "rvest", "cluster", "factoextra", "outliers", "acss", 'asbio','akima', 'plotly', 'factoextra', 'interactions')

#install.packages(util_libraries)
#install.packages(vis_libraries)
#install.packages(stat_libraries)

for (l in 1:length(util_libraries)){ library(util_libraries[l], character.only = TRUE)}
for (l in 1:length(vis_libraries)){ library(vis_libraries[l], character.only = TRUE)}
for (l in 1:length(stat_libraries)){ library(stat_libraries[l], character.only = TRUE)}
```

symbolic transfer entropy
```{r}
#install.packages("remotes")
remotes::install_github("aromeu-source/R-code")
```



Graph theme set
```{r}
theme_set(theme_bw())

dropLeadingZero <- function(l){
  str_replace(l, '0(?=.)', '')
}
```

```{r}
library(robustbase)
library(tidyverse)
library(sandwich)
library(lmtest)
library(modelr)
library(broom)
library(mgcv)

#install.packages('RTransferEntropy')
library(RTransferEntropy)

#install.packages("Greg")
library(Greg) #has confidence intervals for robust SE
```


Clear
```{r}
rm(list=ls())
```


###Read data

Read file
```{r}
moby<-read.csv("moby_data1_17_01_2022.csv")
```



###Test transfer entropy calculations
```{r}
a=c(1,1,1,2,3,4)
b=c(1,1,1,1,3,3)

te_a_to_b <- calc_te(a,b)
te_b_to_a <- calc_te(b,a)

n_perm <- 100
perm_res <- matrix(0,nrow=n_perm, ncol=2)

for (p in 1:n_perm) {
  n <- length(a)
  randvec <- runif(n)
  a_rnd <- a[order(randvec)]
  b_rnd <- b[order(randvec)]
  perm_res[p,1] <- calc_te(a_rnd,b_rnd)
  perm_res[p,2] <- calc_te(b_rnd,a_rnd)
}

te_a_to_b_p <- sum(perm_res[,1]>=te_a_to_b)/n_perm
te_b_to_a_p <- sum(perm_res[,2]>=te_b_to_a)/n_perm

te_a_to_b
te_a_to_b_p 
te_b_to_a
te_b_to_a_p 
```

###Test symbolic transfer entropy calculations
```{r}
a=c(4, 6, 1, 9)
a_tm1 <- c(0,4, 6, 1)
b=c(1, 4, 3, 1)
b_tm1=c(0,4,3,1)

sym <- TECtest::symbolize(a, a_tm1,b,2)
TECtest::TEntropy(sym)$TE

sym <- TECtest::symbolize(b, b_tm1,a,2)
TECtest::TEntropy(sym)$TE
```


```{r}
moby$mixing <- moby$assortativity_rev_z
moby$mixing_z <- (moby$mixing-min(moby$mixing, na.rm=T))/sd(moby$mixing)
moby$bonding <- moby$weighted_cross_edges_ratio_z
moby$bonding_z <- (moby$bonding-min(moby$bonding, na.rm=T))/sd(moby$bonding)
moby$incorporating <- moby$female_coreness_log_z
moby$incorporating_z <- (moby$incorporating-min(moby$incorporating, na.rm=T))/sd(moby$incorporating)

moby$combined <- moby$mixing_z*moby$bonding_z*moby$incorporating_z
```


```{r}
#detach("package:tidyverse", unload=TRUE)
df <- moby

comp_tab <- table(df$org_dev)

comp_names <- as.numeric(names(comp_tab))

n_comp <- length(comp_names)

comp_n_plus <- comp_tab>=4
comp_names_n_plus <- comp_names[comp_n_plus]

comp_names_in_data <- df$org_dev

is_it_n_plus <- comp_names_in_data  %in% comp_names_n_plus

table(is_it_n_plus)

df_n_plus <- df[is_it_n_plus,]

my_vars <- c("org_dev", "year", "game_id", "blau2", "combined", "game_dist_prev5yr")

df_n_plus <- df_n_plus[my_vars]


#recompute company list and n
comp_tab <- table(df_n_plus$org_dev)
comp_names <- as.numeric(names(comp_tab))
n_comp <- length(comp_names)


#generate n versions of the dataset with same-year games randomly sorted within firm
n_rep=500
r=1
data_rows <- dim(df_n_plus)[1]
randvec <- runif(data_rows)
df_n_plus <- df_n_plus[order(df_n_plus$org_dev, df_n_plus$year, randvec),]
df_n_plus$rep_id <- rep(r,data_rows)
df_replicated <- df_n_plus

for (r in 2:n_rep) {
randvec <- runif(data_rows)
df_n_plus <- df_n_plus[order(df_n_plus$org_dev, df_n_plus$year, randvec),]
df_n_plus$rep_id <- rep(r,data_rows)
df_replicated <- rbind(df_replicated, df_n_plus)
}

granger_results2 <- data.frame(matrix(0,nrow=n_comp*n_rep, ncol=20))
granger_results2[,1] <- rep(comp_names,n_rep)
colnames(granger_results2) <- c("company", 
                               "n_games", 
                               "mean_dist",
                               "last_div",
                               "last_inc",
                               "div_trend",
                               "inc_trend",
                               "corr",
                               "grang_div_to_inc_f", 
                               "grang_inc_to_div_f", 
                               "grang_div_to_inc_p", 
                               "grang_inc_to_div_p", 
                               "te_div_to_inc", 
                               "te_inc_to_div",
                               "te_div_to_inc_p", 
                               "te_inc_to_div_p",
                               "te_div_to_inc_diff_p",
                               "te_inc_to_div_diff_p",
                               "te_sym_div_to_inc", 
                               "te_sym_inc_to_div")

counter=1
for (r in 1:n_rep) {
  print(r)
  
  for (i in 1:n_comp) {
    
    comp <- comp_names[i]
    data_slice <- df_replicated[df_replicated$rep_id==r,]
    comp_data = data_slice[data_slice$org_dev == comp,]
    
    comp_data <- comp_data[order(comp_data$year, comp_data$game_id),]
    
    comp_data_rows <- dim(comp_data)[1]
    
    diversity = comp_data$blau2
    inclusion = comp_data$combined
    
    granger_results2[counter, 2] <- comp_data_rows
    
    #means 
    granger_results2[counter, 3] <- mean(comp_data$game_dist_prev5yr)
    granger_results2[counter, 4] <- diversity[comp_data_rows]
    granger_results2[counter, 5] <- inclusion[comp_data_rows]
    
    #year trends
    years <- comp_data$year
    granger_results2[counter, 6] <- lm(diversity ~ years)$coefficients[2]
    granger_results2[counter, 7] <- lm(inclusion ~ years)$coefficients[2]
    
    #correlation of div and inc
    
    c <- cor(diversity,inclusion)
    granger_results2[counter, 8] <- c
    if(is.na(c)){c=1}
    
    #granger prediction test both ways
    
    #granger_results2[counter, 9]  <- if(abs(c)<1 & sum(inclusion>0)>1 & comp_data_rows>=5){grangertest(diversity, inclusion, order=1)$F[2]}else{0}
    #granger_results2[counter, 10] <- if(abs(c)<1 & sum(inclusion>0)>1 & comp_data_rows>=5){grangertest(inclusion, diversity, order=1)$F[2]}else{0}
    
    #granger_results2[counter, 11] <-if(abs(c)<1 & sum(inclusion>0)>1 & comp_data_rows>=5){grangertest(diversity, inclusion, order=1)$`Pr(>F)`[2]}else{1}
    #granger_results2[counter, 12] <-if(abs(c)<1 & sum(inclusion>0)>1 & comp_data_rows>=5){grangertest(inclusion, diversity, order=1)$`Pr(>F)`[2]}else{1}
    
    
    #transfer entropy both ways
    #tr entropy calculation
    te_div_to_inc <- calc_te(diversity, inclusion, lx=1, ly=1, quantiles = c(25,75))
    te_inc_to_div <- calc_te(inclusion, diversity, lx=1, ly=1, quantiles = c(25,75))
    
    
    #symbolic transfer entropy
    #calculate t-1 series
    diversity_tm1 <- c(0,diversity[1:length(diversity)-1])
    inclusion_tm1 <- c(0,inclusion[1:length(inclusion)-1])

    sym <- TECtest::symbolize(diversity, diversity_tm1,inclusion,2)
    te_sym_inc_to_div <- TECtest::TEntropy(sym)$TE

    sym <- TECtest::symbolize(inclusion, inclusion_tm1,diversity,2)
    te_sym_div_to_inc <-  TECtest::TEntropy(sym)$TE
    
 
    #p value calculation
    n_perm <- 1
    perm_res <- matrix(0, nrow = n_perm, ncol = 4)
    
    for (p in 1:n_perm) {
      n <- length(diversity)
      randvec1 <- runif(n)
      randvec2 <- runif(n)
      div_rnd <- diversity[order(randvec1)]
      inc_rnd <- inclusion[order(randvec2)]
      perm_res[p, 1] <- calc_te(div_rnd, inc_rnd, lx=1, ly=1, quantiles = c(25,75))
      perm_res[p, 2] <- calc_te(inc_rnd, div_rnd, lx=1, ly=1, quantiles = c(25,75))
      perm_res[p, 3] <- perm_res[p, 1]-perm_res[p, 2]
      perm_res[p, 4] <- perm_res[p, 2]-perm_res[p, 1]
    }
    
    te_div_to_inc_p <- sum(perm_res[, 1] >= te_div_to_inc) / n_perm
    te_inc_to_div_p <- sum(perm_res[, 2] >= te_inc_to_div) / n_perm
    
    te_div_to_inc_diff_p <- sum(perm_res[, 3] >= te_div_to_inc-te_inc_to_div) / n_perm
    te_inc_to_div_diff_p <- sum(perm_res[, 2] >= te_inc_to_div-te_div_to_inc) / n_perm
    
    granger_results2[counter, 13] <- te_div_to_inc
    granger_results2[counter, 14] <- te_inc_to_div
    
    granger_results2[counter, 15] <- te_div_to_inc_p
    granger_results2[counter, 16] <- te_inc_to_div_p
    
    granger_results2[counter, 17] <- te_div_to_inc_diff_p
    granger_results2[counter, 18] <- te_inc_to_div_diff_p
    
    granger_results2[counter, 19] <- te_sym_div_to_inc
    granger_results2[counter, 20] <- te_sym_inc_to_div    
    
    counter=counter+1
  }#end one dataset
  
}#end replications loop
  
```


###Comparing full dataset and trajectories subsample
```{r}
length(unique(moby$org_dev))

n_comp

length(moby$name)

length(df_n_plus$name)

mean(moby$game_dist_prev5yr)
mean(df_n_plus$game_dist_prev5yr)

ks.test(moby$game_dist_prev5yr, df_n_plus$game_dist_prev5yr)
wilcox.test(moby$game_dist_prev5yr, df_n_plus$game_dist_prev5yr, alternative = "two.sided")

mean(moby$blau2)
mean(df_n_plus$blau2)

ks.test(moby$blau2, df_n_plus$blau2)
wilcox.test(moby$blau2, df_n_plus$blau2, alternative = "two.sided")

mean(moby$combined)
mean(df_n_plus$combined)

ks.test(moby$combined, df_n_plus$combined)
wilcox.test(moby$combined, df_n_plus$combined, alternative = "two.sided")


```

```{r, fig.width = 3.6, fig.height = 2.2}

dropLeadingZero <- function(l){
  str_replace(l, '0(?=.)', '')
}

df <- granger_results2[granger_results2$te_div_to_inc_p<.1 & granger_results2$n_games<=7,]

best_comp_div_to_inc <- unique(df$company[(df$te_div_to_inc)==max(df$te_div_to_inc)])[1]

score_div_to_inc <- max(df$te_div_to_inc)

df <- granger_results2[granger_results2$te_inc_to_div_p<.1 & granger_results2$n_games<=7,]

best_comp_inc_to_div <- unique(df$company[(df$te_inc_to_div)==max(df$te_inc_to_div)])[1]

score_inc_to_div <- max(df$te_inc_to_div)

#best_comp_div_to_inc <- unique(df$company[(df$te_div_to_inc)==max(df$te_div_to_inc)])[1]
#best_comp_inc_to_div <- unique(df$company[(df$te_inc_to_div)==max(df$te_inc_to_div)])[1]

df_div_to_inc <- df_n_plus[df_n_plus$org_dev==best_comp_div_to_inc,]
df_div_to_inc$time <- seq(dim(df_div_to_inc)[1])
#df_div_to_inc$combined <- df_div_to_inc$mixing*df_div_to_inc$bonding*df_div_to_inc$incorporating
df_div_to_inc$combined <- (df_div_to_inc$combined-mean(df_div_to_inc$combined))/sd(df_div_to_inc$combined)
df_div_to_inc$blau2 <- (df_div_to_inc$blau2-mean(df_div_to_inc$blau2))/sd(df_div_to_inc$blau2)

df_inc_to_div <- df_n_plus[df_n_plus$org_dev==best_comp_inc_to_div,]
df_inc_to_div$time <- seq(dim(df_inc_to_div)[1])
#df_inc_to_div$combined <- df_inc_to_div$mixing*df_inc_to_div$bonding*df_inc_to_div$incorporating
df_inc_to_div$combined <- (df_inc_to_div$combined-mean(df_inc_to_div$combined))/sd(df_inc_to_div$combined)
df_inc_to_div$blau2 <- (df_inc_to_div$blau2-mean(df_inc_to_div$blau2))/sd(df_inc_to_div$blau2)




hi_color = "#b4de75"
lo_color = "#69629a"

m_top <- 2
m_left <-0
m_bottom <- 0
m_right <- 0
ts <- 3.2
tit_s <- 11
iqr_alpha <- 0.07
ribbon_alpha <- 0.33



example_div_to_inc <- ggplot() +
  
  geom_point(data=df_div_to_inc, aes(x=time, y=combined), color=hi_color) + 
  geom_line(data=df_div_to_inc, aes(x=time, y=combined), color=hi_color) +
  
  geom_point(data=df_div_to_inc, aes(x=time, y=blau2), color=lo_color) + 
  geom_line(data=df_div_to_inc, aes(x=time, y=blau2), color=lo_color) +
  
  scale_x_continuous(breaks=seq(dim(df_div_to_inc)[1]), labels = dropLeadingZero) +
  scale_y_continuous(labels = dropLeadingZero) +
  
    xlab("Time") +
    ylab("Z-score") +
    ggtitle("a: Diversity driven\nprocess") +
  
    annotate(geom="text", x=1,    y=1, label="Diversity", lineheight = .8,  col=lo_color, size=3.3, hjust = 0, alpha = 1) +
    annotate(geom="text", x=1.8,    y=.25, label="Inclusion", lineheight = .8,  col=hi_color, size=3.3, hjust = 0, alpha = 1) +
  
    #theme
  theme(aspect.ratio=1,
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black",
                                        fill=NA,
                                        size=0.2),
            legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            #axis.ticks.y = element_blank(),
            axis.title.y = element_text(size = 11, colour = "black"),
            axis.text.x = element_text(size = 9, colour = "black"),
            axis.text.y = element_text(size = 9, colour = "black"),
            plot.margin = unit(c(m_top,m_right,m_bottom,m_left), "mm")
            )
  
example_inc_to_div <- ggplot() +
  
  geom_point(data=df_inc_to_div, aes(x=time, y=combined), color=hi_color) + 
  geom_line(data=df_inc_to_div, aes(x=time, y=combined), color=hi_color) +
  
  geom_point(data=df_inc_to_div, aes(x=time, y=blau2), color=lo_color) + 
  geom_line(data=df_inc_to_div, aes(x=time, y=blau2), color=lo_color) +
  
  annotate(geom="text", x=1.8,    y=-1, label="Diversity", lineheight = .8,  col=lo_color, size=3.3, hjust = 0, alpha = 1) +
  annotate(geom="text", x=1.8,    y=1.1, label="Inclusion", lineheight = .8,  col=hi_color, size=3.3, hjust = 0, alpha = 1) +
  
  scale_x_continuous(breaks=seq(dim(df_inc_to_div)[1]), labels = dropLeadingZero) +
  scale_y_continuous(labels = dropLeadingZero) +
  
    xlab("Time") +
    ylab("") +
    ggtitle("b: Inclusion driven\nprocess") +
  
  #theme
  theme(aspect.ratio=1,
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black",
                                        fill=NA,
                                        size=0.2),
            legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            #axis.ticks.y = element_blank(),
            axis.title.y = element_text(size = 11, colour = "black"),
            axis.text.x = element_text(size = 9, colour = "black"),
            axis.text.y = element_text(size = 9, colour = "black"),
            plot.margin = unit(c(m_top,m_right,m_bottom,m_left-4), "mm")
            )

examples_combined <- cowplot::plot_grid(example_div_to_inc, example_inc_to_div, align="h", rel_heights = 1, scale=1)
examples_combined

```

```{r}
ggsave("process_examples.pdf", examples_combined, width = 3.6, height = 2.2)
```


```{r}
granger_results2_ag <- aggregate(granger_results2, list(company2 =granger_results2$company), mean)
granger_results2_ag_median <- aggregate(granger_results2, list(company2 =granger_results2$company), median)
```


```{r, fig.width = 10.9, fig.height = 5}
hi_color = "#b4de75"
lo_color = "#69629a"

m_top <- 0
m_left <-4
m_bottom <- 0
m_right <- 4
ts <- 3.2
tit_s <- 11
iqr_alpha <- 0.07
ribbon_alpha <- 0.33

df=granger_results2

final_inclusion <- ggplot(df) + 
  #geom_point( aes(x = te_div_to_inc, y = last_inc),  na.rm=T, col = 'blue', alpha=0.3) +
  geom_smooth(aes(x = te_div_to_inc, y = last_inc),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col="darkgreen", fill=hi_color, alpha=ribbon_alpha) +
  geom_smooth(aes(x = te_inc_to_div, y = last_inc),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col=lo_color, fill=lo_color, alpha=ribbon_alpha) +
  labs(y= "Final inclusion", x = "Transfer entropy") +
  scale_x_continuous(expand=c(0,0), limits = c(0, 1)) +
  scale_y_continuous(expand=c(0,0)) +
  annotate(geom="text", x=0.7,    y=17.7, label="Diversity\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = 42) +
  annotate(geom="text", x=0.7,    y=15.2, label="Inclusion\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = 4.5) +

  
  #theme
  theme(aspect.ratio=1,
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black",
                                        fill=NA,
                                        size=0.2),
            legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            #axis.ticks.y = element_blank(),
            axis.title.y = element_text(size = 11, colour = "black"),
            axis.text.x = element_text(size = 9, colour = "black"),
            axis.text.y = element_text(size = 9, colour = "black"),
            plot.margin = unit(c(m_top,m_right,m_bottom,m_left), "mm")
            )
  
final_diversity <- ggplot(df) + 
  #geom_point( aes(x = te_div_to_inc, y = last_inc),  na.rm=T, col = 'blue', alpha=0.3) +
  geom_smooth(aes(x = te_div_to_inc, y = last_div),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col="darkgreen", fill=hi_color, alpha=ribbon_alpha) +
  geom_smooth(aes(x = te_inc_to_div, y = last_div),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col=lo_color, fill=lo_color, alpha=ribbon_alpha) +
  labs(y= "Final diversity", x = "Transfer entropy") +
  scale_x_continuous(expand=c(0,0), limits = c(0, 1)) +
  scale_y_continuous(expand=c(0,0)) +
  annotate(geom="text", x=0.7,    y=.265, label="Diversity\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = 42) +
  annotate(geom="text", x=0.7,    y=.254, label="Inclusion\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = 22) +
    
  #theme
  theme(aspect.ratio=1,
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black",
                                        fill=NA,
                                        size=0.2),
            legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            #axis.ticks.y = element_blank(),
            axis.title.y = element_text(size = 11, colour = "black"),
            axis.text.x = element_text(size = 9, colour = "black"),
            axis.text.y = element_text(size = 9, colour = "black"),
            plot.margin = unit(c(m_top,m_right,m_bottom,m_left), "mm")
            )

final_combined <- cowplot::plot_grid(final_inclusion, final_diversity, align="h", rel_heights = 1, scale=1)
final_combined
```

```{r, fig.width = 10.9, fig.height = 5}
hi_color = "#b4de75"
lo_color = "#69629a"

m_top <- 2
m_left <-0
m_bottom <- 0
m_right <- 4
ts <- 3.2
tit_s <- 11
iqr_alpha <- 0.07
ribbon_alpha <- 0.33

df=granger_results2

trend_inclusion <- ggplot(df) + 
  #geom_point( aes(x = te_div_to_inc, y = last_inc),  na.rm=T, col = 'blue', alpha=0.3) +
  geom_smooth(aes(x = te_div_to_inc, y = inc_trend),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col="darkgreen", fill=hi_color, alpha=ribbon_alpha) +
  geom_smooth(aes(x = te_inc_to_div, y = inc_trend),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col=lo_color, fill=lo_color, alpha=ribbon_alpha) +
  labs(y= "Trend of inclusion", x = "Transfer entropy") +
  scale_x_continuous(expand=c(0,0), limits = c(0, 1), labels = dropLeadingZero) +
  scale_y_continuous(expand=c(0,0), labels = dropLeadingZero) +
  annotate(geom="text", x=0.7,    y=0.95, label="Diversity\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = 42) +
  annotate(geom="text", x=0.7,    y=0.059, label="Inclusion\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = -2) +

  
  #theme
  theme(aspect.ratio=1, 
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            panel.border = element_rect(colour = "black", 
                                        fill=NA, 
                                        size=0.2),
            legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            #axis.ticks.y = element_blank(),
            axis.title.y = element_text(size = 11, colour = "black"),
            axis.text.x = element_text(size = 9, colour = "black"),
            axis.text.y = element_text(size = 9, colour = "black"),
            plot.margin = unit(c(m_top,m_right,m_bottom,0), "mm")
            )
  
trend_diversity <- ggplot(df) + 
  #geom_point( aes(x = te_div_to_inc, y = last_inc),  na.rm=T, col = 'blue', alpha=0.3) +
  geom_smooth(aes(x = te_div_to_inc, y = div_trend),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col="darkgreen", fill=hi_color, alpha=ribbon_alpha) +
  geom_smooth(aes(x = te_inc_to_div, y = div_trend),  na.rm=T, method="lm", span = 1, formula = 'y ~ x', col=lo_color, fill=lo_color, alpha=ribbon_alpha) +
  labs(y= "Trend of diversity", x = "Transfer entropy") +
  scale_x_continuous(expand=c(0,0), limits = c(0, 1), labels = dropLeadingZero) +
  scale_y_continuous(expand=c(0,0), labels = dropLeadingZero) +
  annotate(geom="text", x=0.7,    y=.006, label="Diversity\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = 41) +
  annotate(geom="text", x=0.7,    y=.0032, label="Inclusion\ndriven process", lineheight = .8,  col="black", size=3.2, hjust = 0.5, alpha = 1, angle = -2) +
    
  #theme
  theme(aspect.ratio=1, 
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            panel.border = element_rect(colour = "black", 
                                        fill=NA, 
                                        size=0.2),
            legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            #axis.ticks.y = element_blank(),
            axis.title.y = element_text(size = 11, colour = "black"),
            axis.text.x = element_text(size = 9, colour = "black"),
            axis.text.y = element_text(size = 9, colour = "black"),
            plot.margin = unit(c(m_top,m_right,m_bottom,0), "mm")
            )

trend_combined <- cowplot::plot_grid(trend_inclusion, trend_diversity, align="h", rel_heights = 1)
trend_combined
```
```{r, message=FALSE, warning = FALSE}
moby_dev_firm_level <- aggregate(moby, list(dev_firm = moby$org_dev), mean)
```


```{r}
granger_results2$last_inc_z <- (granger_results2$last_inc-mean(granger_results2$last_inc))/sd(granger_results2$last_inc)
granger_results2$last_div_z <- (granger_results2$last_div-mean(granger_results2$last_div))/sd(granger_results2$last_div)
granger_results2$inc_trend_z <- (granger_results2$inc_trend-mean(granger_results2$inc_trend))/sd(granger_results2$inc_trend)
granger_results2$div_trend_z <- (granger_results2$div_trend-mean(granger_results2$div_trend))/sd(granger_results2$div_trend)
granger_results2$te_inc_to_div_z <- (granger_results2$te_inc_to_div-mean(granger_results2$te_inc_to_div))/sd(granger_results2$te_inc_to_div)
granger_results2$te_div_to_inc_z <- (granger_results2$te_div_to_inc-mean(granger_results2$te_div_to_inc))/sd(granger_results2$te_div_to_inc)

granger_results2_ag$last_inc_z <- (granger_results2_ag$last_inc-mean(granger_results2_ag$last_inc))/sd(granger_results2_ag$last_inc)
granger_results2_ag$last_div_z <- (granger_results2_ag$last_div-mean(granger_results2_ag$last_div))/sd(granger_results2_ag$last_div)
granger_results2_ag$inc_trend_z <- (granger_results2_ag$inc_trend-mean(granger_results2_ag$inc_trend))/sd(granger_results2_ag$inc_trend)
granger_results2_ag$div_trend_z <- (granger_results2_ag$div_trend-mean(granger_results2_ag$div_trend))/sd(granger_results2_ag$div_trend)
granger_results2_ag$te_inc_to_div_z <- (granger_results2_ag$te_inc_to_div-mean(granger_results2_ag$te_inc_to_div))/sd(granger_results2_ag$te_inc_to_div)
granger_results2_ag$te_div_to_inc_z <- (granger_results2_ag$te_div_to_inc-mean(granger_results2_ag$te_div_to_inc))/sd(granger_results2_ag$te_div_to_inc)


granger_results2_ag$te_sym_inc_to_div_z <- (granger_results2_ag$te_sym_inc_to_div-mean(granger_results2_ag$te_sym_inc_to_div))/sd(granger_results2_ag$te_sym_inc_to_div)
granger_results2_ag$te_sym_div_to_inc_z <- (granger_results2_ag$te_sym_div_to_inc-mean(granger_results2_ag$te_sym_div_to_inc))/sd(granger_results2_ag$te_sym_div_to_inc)


granger_results2_ag_median$last_inc_z <- (granger_results2_ag_median$last_inc-mean(granger_results2_ag_median$last_inc))/sd(granger_results2_ag_median$last_inc)
granger_results2_ag_median$last_div_z <- (granger_results2_ag_median$last_div-mean(granger_results2_ag_median$last_div))/sd(granger_results2_ag_median$last_div)
granger_results2_ag_median$inc_trend_z <- (granger_results2_ag_median$inc_trend-mean(granger_results2_ag_median$inc_trend))/sd(granger_results2_ag_median$inc_trend)
granger_results2_ag_median$div_trend_z <- (granger_results2_ag_median$div_trend-mean(granger_results2_ag_median$div_trend))/sd(granger_results2_ag_median$div_trend)
granger_results2_ag_median$te_inc_to_div_z <- (granger_results2_ag_median$te_inc_to_div-mean(granger_results2_ag_median$te_inc_to_div))/sd(granger_results2_ag_median$te_inc_to_div)
granger_results2_ag_median$te_div_to_inc_z <- (granger_results2_ag_median$te_div_to_inc-mean(granger_results2_ag_median$te_div_to_inc))/sd(granger_results2_ag_median$te_div_to_inc)

moby_dev_firm_level$company <- moby_dev_firm_level$dev_firm

firm_level <- inner_join(granger_results2_ag, moby_dev_firm_level, by="company")
firm_level_median <- inner_join(granger_results2_ag_median, moby_dev_firm_level, by="company")

plot(granger_results2_ag$te_div_to_inc_z, granger_results2_ag$te_sym_inc_to_div_z)
```
```{r}
write.csv(firm_level, "firm_level.csv")
```


#company creativity sequences
relative firm time
```{r}
n_row <- dim(df_n_plus)[1]

df_n_plus$time <- 0

for (i in 1:(n_row-1)) {
  
  if(df_n_plus$org_dev[i]==df_n_plus$org_dev[i+1]){
    df_n_plus$time[i]<-counter
    counter=counter+1
  }else{counter=1}
}
```



```{r}

df_n_plus$combined_z <- (df_n_plus$combined-mean(df_n_plus$combined, na.rm=T))/sd(df_n_plus$combined)
df_n_plus$blau2_z <- (df_n_plus$blau2-mean(df_n_plus$blau2, na.rm=T))/sd(df_n_plus$blau2)
df_n_plus$game_dist_prev5yr_z <- (df_n_plus$game_dist_prev5yr-mean(df_n_plus$game_dist_prev5yr, na.rm=T))/sd(df_n_plus$game_dist_prev5yr)

df=df_n_plus[df_n_plus$time<=10 & df_n_plus$time>=1,]



ggplot(data=df) +
  geom_smooth(aes(x = time, y = game_dist_prev5yr_z),  na.rm=T, method="loess", span = 0.5, formula = 'y ~ x', col="red", fill="red", alpha=ribbon_alpha)+
  geom_smooth(aes(x = time, y = combined_z),  na.rm=T, method="loess", span = 0.5, formula = 'y ~ x', col="darkgreen", fill=hi_color, alpha=ribbon_alpha)+
  geom_smooth(aes(x = time, y = blau2_z),  na.rm=T, method="loess", span = 0.5, formula = 'y ~ x', col="blue", fill=lo_color, alpha=ribbon_alpha) +
  
  scale_x_continuous(expand=c(0,0), breaks = seq(1,10,1)) +
  scale_y_continuous(expand=c(0,0), labels = dropLeadingZero)

```




```{r}
#summary(lm(last_inc_z ~ te_div_to_inc_z + te_inc_to_div_z + n_games, data = granger_results2))
#summary(lm(last_div_z ~ te_div_to_inc_z + te_inc_to_div_z + n_games, data = granger_results2))

#summary(lm(inc_trend_z ~ te_div_to_inc_z + te_inc_to_div_z + n_games, data = granger_results2))
#summary(lm(div_trend_z ~ te_div_to_inc_z + te_inc_to_div_z + n_games, data = granger_results2))




m_last_inc <- lm(
  last_inc_z ~
    te_div_to_inc_z +
    te_inc_to_div_z +
    
    n_games +
    #newbies_prop +
    #games_tenure +
    #star_prior  +
    #hold_single_firm +
    #ratio_core_z +
    #num_countries +
    #plat2 + plat7 + plat12 + plat13 + plat14 + plat15 +
    year13 + year15 + year16 + year17 + year18 + year19 + year20 + year21 + year22 + year23 + year24 + year25 + year26 + year27 + year28
    ,
  data = firm_level
)


m_last_div <- lm(
  last_div_z ~
    te_div_to_inc_z +
    te_inc_to_div_z +
    
    n_games +
    # newbies_prop +
    # games_tenure +
    # star_prior  +
    # hold_single_firm +
    # ratio_core_z +
    # num_countries +
    # plat2 + plat7 + plat12 + plat13 + plat14 + plat15 +
    year13 + year15 + year16 + year17 + year18 + year19 + year20 + year21 + year22 + year23 + year24 + year25 + year26 + year27 + year28
    ,
  data = firm_level
)


m_trend_inc <- lm(
  inc_trend_z ~
    te_div_to_inc_z +
    te_inc_to_div_z +
    
    n_games +
    # newbies_prop +
    # games_tenure +
    # star_prior  +
    # hold_single_firm +
    # ratio_core_z +
    # num_countries +
    # plat2 + plat7 + plat12 + plat13 + plat14 + plat15 +
    year13 + year15 + year16 + year17 + year18 + year19 + year20 + year21 + year22 + year23 + year24 + year25 + year26 + year27 + year28
    ,
  data = firm_level
)


m_trend_div <- lm(
  div_trend_z ~
    te_div_to_inc_z +
    te_inc_to_div_z +
    
    n_games +
    # newbies_prop +
    # games_tenure +
    # star_prior  +
    # hold_single_firm +
    # ratio_core_z +
    # num_countries +
    # plat2 + plat7 + plat12 + plat13 + plat14 + plat15 +
    year13 + year15 + year16 + year17 + year18 + year19 + year20 + year21 + year22 + year23 + year24 + year25 + year26 + year27 + year28
    ,
  data = firm_level
)

# Adjust standard errors
cov1         <- vcovHC(m_last_inc, type = "HC1")
m_last_inc_robust_se    <- sqrt(diag(cov1))

cov1         <- vcovHC(m_last_div, type = "HC1")
m_last_div_robust_se    <- sqrt(diag(cov1))

cov1         <- vcovHC(m_trend_inc, type = "HC1")
m_trend_inc_robust_se    <- sqrt(diag(cov1))

cov1         <- vcovHC(m_trend_div, type = "HC1")
m_trend_div_robust_se    <- sqrt(diag(cov1))

# Stargazer output (with and without RSE)
stargazer(m_last_inc,
          column.labels='Base model',
          type="text", 
          keep = c("te_d*", "te_i*"), 
          se = list(NULL, m_last_inc_robust_se),
          omit.stat = c("f", "ser")
          )

stargazer(m_last_div,
          column.labels='Base model',
          type="text", 
          keep = c("te_d*", "te_i*"), 
          se = list(NULL, m_last_div_robust_se),
          omit.stat = c("f", "ser")
          )

stargazer(m_trend_inc,
          column.labels='Base model',
          type="text", 
          keep = c("te_d*", "te_i*"), 
          se = list(NULL, m_trend_inc_robust_se),
          omit.stat = c("f", "ser")
          )

stargazer(m_trend_div,
          column.labels='Base model',
          type="text", 
          keep = c("te_d*", "te_i*"), 
          se = list(NULL, m_trend_div_robust_se),
          omit.stat = c("f", "ser")
          )
```





```{r}
h <- hist(firm_level$n_games, breaks=100)
h
```



#Point estimates

```{r}
#get model coefs with 95% CI
point_est_m_last_inc_var1 <- data.frame(m_last_inc$coefficients[2] ,confint_robust(m_last_inc, 2, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_last_inc_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_last_inc_var2 <- data.frame(m_last_inc$coefficients[3] ,confint_robust(m_last_inc, 3, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_last_inc_var2) <- c("estim", "ci_025", "ci_975")

point_est_m_last_div_var1 <- data.frame(m_last_div$coefficients[2] ,confint_robust(m_last_div, 2, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_last_div_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_last_div_var2 <- data.frame(m_last_div$coefficients[3] ,confint_robust(m_last_div, 3, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_last_div_var2) <- c("estim", "ci_025", "ci_975")

point_est_m_trend_inc_var1 <- data.frame(m_trend_inc$coefficients[2] ,confint_robust(m_trend_inc, 2, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_trend_inc_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_trend_inc_var2 <- data.frame(m_trend_inc$coefficients[3] ,confint_robust(m_trend_inc, 3, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_trend_inc_var2) <- c("estim", "ci_025", "ci_975")

point_est_m_trend_div_var1 <- data.frame(m_trend_div$coefficients[2] ,confint_robust(m_trend_div, 2, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_trend_div_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_trend_div_var2 <- data.frame(m_trend_div$coefficients[3] ,confint_robust(m_trend_div, 3, HC_type = "HC3", t_distribution = FALSE,level=0.95))
colnames(point_est_m_trend_div_var2) <- c("estim", "ci_025", "ci_975")
```

```{r}
#get model coefs with 95% CI
point_est_m_last_inc_var1 <- data.frame(m_last_inc$coefficients[2] ,confint(m_last_inc, 2,level=0.95))
colnames(point_est_m_last_inc_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_last_inc_var2 <- data.frame(m_last_inc$coefficients[3] ,confint(m_last_inc, 3,level=0.95))
colnames(point_est_m_last_inc_var2) <- c("estim", "ci_025", "ci_975")

point_est_m_last_div_var1 <- data.frame(m_last_div$coefficients[2] ,confint(m_last_div, 2,level=0.95))
colnames(point_est_m_last_div_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_last_div_var2 <- data.frame(m_last_div$coefficients[3] ,confint(m_last_div, 3,level=0.95))
colnames(point_est_m_last_div_var2) <- c("estim", "ci_025", "ci_975")

point_est_m_trend_inc_var1 <- data.frame(m_trend_inc$coefficients[2] ,confint(m_trend_inc, 2,level=0.95))
colnames(point_est_m_trend_inc_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_trend_inc_var2 <- data.frame(m_trend_inc$coefficients[3] ,confint(m_trend_inc, 3,level=0.95))
colnames(point_est_m_trend_inc_var2) <- c("estim", "ci_025", "ci_975")

point_est_m_trend_div_var1 <- data.frame(m_trend_div$coefficients[2] ,confint(m_trend_div, 2,level=0.95))
colnames(point_est_m_trend_div_var1) <- c("estim", "ci_025", "ci_975")
point_est_m_trend_div_var2 <- data.frame(m_trend_div$coefficients[3] ,confint(m_trend_div, 3,level=0.95))
colnames(point_est_m_trend_div_var2) <- c("estim", "ci_025", "ci_975")
```




```{r}
install.packages("extrafont")
library(extrafont)
#font_import()
#fonts()
```



```{r, fig.width = 2.8, fig.height = 1.55}


s <- 3
ps <- 2.85
tit_s <- 12
asp <- 0.6

m_top <- 1
m_left <-0
m_bottom <- -4
m_right <- 0

lab_y=-0.08

ols_estim_process <- ggplot()+
  geom_hline(yintercept = 0, linetype="dashed", alpha=0.7, color="black", size=0.2) +
  
  #te_div_to_inc_z

  geom_errorbar(data = point_est_m_last_div_var1, aes(x = 1.3, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_last_div_var1, aes(x = 1.3, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=1.3,    y=point_est_m_last_div_var1$estim, label="1",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  geom_errorbar(data = point_est_m_last_inc_var1, aes(x=1.1, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_last_inc_var1, aes(x=1.1, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=1.1,    y=point_est_m_last_inc_var1$estim, label="2",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  geom_errorbar(data = point_est_m_trend_div_var1, aes(x = 0.9, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_trend_div_var1, aes(x = 0.9, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=0.9,    y=point_est_m_trend_div_var1$estim, label="3",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  geom_errorbar(data = point_est_m_trend_inc_var1, aes(x = 0.7, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_trend_inc_var1, aes(x = 0.7, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=0.7,    y=point_est_m_trend_inc_var1$estim, label="4",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  
  #te_inc_to_div_z

  
  geom_errorbar(data = point_est_m_last_div_var2, aes(x = 2.3, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_last_div_var2, aes(x = 2.3, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=2.3,    y=point_est_m_last_div_var2$estim, label="1",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  geom_errorbar(data = point_est_m_last_inc_var2, aes(x=2.1, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_last_inc_var2, aes(x=2.1, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=2.1,    y=point_est_m_last_inc_var2$estim, label="2",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  geom_errorbar(data = point_est_m_trend_div_var2, aes(x = 1.9, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_trend_div_var2, aes(x = 1.9, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=1.9,    y=point_est_m_trend_div_var2$estim, label="3",   col="white", size=s, hjust = 0.5, alpha = 1) +
  
  geom_errorbar(data = point_est_m_trend_inc_var2, aes(x = 1.7, ymin = ci_025, ymax = ci_975), width=0, alpha=1, color="black", size=0.75) +
  geom_point(   data = point_est_m_trend_inc_var2, aes(x = 1.7, estim), alpha=1, color="black", shape=21, fill="black", size=ps, stroke=1) +
  annotate(geom="text", x=1.7,    y=point_est_m_trend_inc_var2$estim, label="4",   col="white", size=s, hjust = 0.5, alpha = 1) +
  


  
  #explain

    
  annotate(geom="text", x=1.3,    y=lab_y, label="Final diversity", lineheight = .7,   col="grey50", size=2.9, hjust = 1, alpha = 1) +
  geom_segment(aes(y=lab_y+.01,    x=1.3, yend = point_est_m_last_div_var1$ci_025-.01, xend = 1.3),size=0.3, col = "grey50", alpha=0.66, linetype=3) +
  
  annotate(geom="text", x=1.1,    y=lab_y, label="Final inclusion", lineheight = .7,   col="grey50", size=2.9, hjust = 1, alpha = 1) +
  geom_segment(aes(y=lab_y+.01,    x=1.1, yend = point_est_m_last_inc_var1$ci_025-.01, xend = 1.1),size=0.3, col = "grey50", alpha=0.66, linetype=3) +
  
  annotate(geom="text", x=0.9,    y=lab_y, label="Trend of diversity", lineheight = .7,   col="grey50", size=2.9, hjust = 1, alpha = 1) +
  geom_segment(aes(y=lab_y+.01,    x=0.9, yend = point_est_m_trend_div_var1$ci_025-.01, xend = 0.9),size=0.3, col = "grey50", alpha=0.66, linetype=3) +
  
  annotate(geom="text", x=0.7,    y=lab_y, label="Trend of inclusion", lineheight = .7,   col="grey50", size=2.9, hjust = 1, alpha = 1) +
  geom_segment(aes(y=lab_y+.01,    x=0.7, yend = point_est_m_trend_inc_var1$ci_025-.01, xend = 0.7),size=0.3, col = "grey50", alpha=0.66, linetype=3) +

  
  
  geom_vline(xintercept = 1.5, linetype="solid", alpha=0.7, color="black", size=0.2) +
  #geom_vline(xintercept = 2.5, linetype="solid", alpha=0.7, color="black", size=0.2) +
  #geom_vline(xintercept = 3.425, linetype="solid", alpha=0.7, color="black", size=0.2) +
  #geom_vline(xintercept = 4.425, linetype="solid", alpha=0.7, color="black", size=0.2) +

  #scale_x_continuous(breaks=(1:2), expand = c(0.05,0.05), labels=c("Diversity\ndriven\nprocess", "Inclusion\ndriven\nprocess")) +
  scale_x_continuous(
                     breaks=(1:2), 
                     expand = c(0.05,0.05), 
                     labels=c(
                       expression(paste(italic(T[D %->% I]))), 
                       expression(paste(italic(T[I %->% D])))
                       )
                     ) +    
  scale_y_continuous(breaks=c(-0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3), labels = dropLeadingZero) +
  #coord_cartesian(ylim = c(-0.2, 0.2)) +
  
   labs(y="") +
  #ggtitle("a: Game level") + 
  #scale_y_continuous(breaks=seq(-0.4, 0.2, 0.1))+
  coord_flip(ylim = c(-.37, .32)) +
  theme(aspect.ratio=asp, 
            title =element_text(size=11, face='bold'),
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), 
            panel.background = element_blank(), 
            panel.border = element_rect(colour = "black", 
                                        fill=NA, 
                                        size=0.2),
            #legend.position = c(0.2, 0.3),
            plot.title = element_text(size = tit_s, face = "bold", colour = "black"),
            axis.ticks.y = element_blank(),
            axis.title.y = element_blank(),
            axis.text.y = element_text(size = 14, colour = "black", face = "bold.italic"),
            plot.margin = unit(c(m_top,m_right,m_bottom,m_left), "mm")
            )
  

#grid.newpage()
ols_estim_process
```


```{r}
ggsave("ols_estim_process.pdf", ols_estim_process, width = 2.8, height = 1.55)
```

